<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuBuilderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin_menus = [
            [
                'id' => 1,
                'name' => 'main_menu',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'footer_menu_1',
                'created_at' => '2024-08-03 22:35:26',
                'updated_at' => '2024-08-03 22:35:26',
            ],
            [
                'id' => 3,
                'name' => 'footer_menu_2',
                'created_at' => '2024-08-03 22:35:39',
                'updated_at' => '2024-08-03 22:35:39',
            ],
            [
                'id' => 4,
                'name' => 'footer_menu_3',
                'created_at' => '2024-08-03 22:36:21',
                'updated_at' => '2024-08-03 22:36:21',
            ],
        ];


        $admin_menu_items = [
            [
                'id' => 1,
                'label' => 'Home',
                'link' => '/',
                'parent_id' => 0,
                'sort' => 0,
                'class' => null,
                'menu_id' => 2,
                'depth' => 0,
                'created_at' => '2024-08-03 22:50:01',
                'updated_at' => '2024-08-03 22:52:25',
            ],
            [
                'id' => 2,
                'label' => 'About',
                'link' => '/about',
                'parent_id' => 0,
                'sort' => 1,
                'class' => null,
                'menu_id' => 2,
                'depth' => 0,
                'created_at' => '2024-08-03 22:53:58',
                'updated_at' => '2024-08-03 22:53:58',
            ],
            [
                'id' => 3,
                'label' => 'Contact',
                'link' => '/contact',
                'parent_id' => 0,
                'sort' => 2,
                'class' => null,
                'menu_id' => 2,
                'depth' => 0,
                'created_at' => '2024-08-03 23:24:05',
                'updated_at' => '2024-08-03 23:24:05',
            ],
            [
                'id' => 4,
                'label' => 'Galery',
                'link' => '/gallery',
                'parent_id' => 0,
                'sort' => 3,
                'class' => null,
                'menu_id' => 2,
                'depth' => 0,
                'created_at' => '2024-08-03 23:24:20',
                'updated_at' => '2024-08-03 23:24:20',
            ],
            [
                'id' => 5,
                'label' => 'Our Service',
                'link' => '/service',
                'parent_id' => 0,
                'sort' => 4,
                'class' => null,
                'menu_id' => 2,
                'depth' => 0,
                'created_at' => '2024-08-03 23:24:35',
                'updated_at' => '2024-08-03 23:24:35',
            ],
            [
                'id' => 6,
                'label' => 'Terms and Conditions',
                'link' => '/terms',
                'parent_id' => 0,
                'sort' => 0,
                'class' => null,
                'menu_id' => 3,
                'depth' => 0,
                'created_at' => '2024-08-03 23:25:00',
                'updated_at' => '2024-08-03 23:25:14',
            ],
            [
                'id' => 7,
                'label' => 'Privacy Policy',
                'link' => '/policy',
                'parent_id' => 0,
                'sort' => 1,
                'class' => null,
                'menu_id' => 3,
                'depth' => 0,
                'created_at' => '2024-08-03 23:25:14',
                'updated_at' => '2024-08-03 23:25:28',
            ],
            [
                'id' => 8,
                'label' => 'Refund Policy',
                'link' => '/refund',
                'parent_id' => 0,
                'sort' => 2,
                'class' => null,
                'menu_id' => 3,
                'depth' => 0,
                'created_at' => '2024-08-03 23:25:28',
                'updated_at' => '2024-08-03 23:25:39',
            ],
            [
                'id' => 9,
                'label' => 'FAQ',
                'link' => '/faq',
                'parent_id' => 0,
                'sort' => 3,
                'class' => null,
                'menu_id' => 3,
                'depth' => 0,
                'created_at' => '2024-08-03 23:25:39',
                'updated_at' => '2024-08-03 23:25:51',
            ],
            [
                'id' => 10,
                'label' => 'Contact',
                'link' => '/contact',
                'parent_id' => 0,
                'sort' => 5,
                'class' => null,
                'menu_id' => 3,
                'depth' => 0,
                'created_at' => '2024-08-03 23:25:51',
                'updated_at' => '2024-08-03 23:25:51',
            ],
            [
                'id' => 11,
                'label' => 'FAQs',
                'link' => '/faq',
                'parent_id' => 0,
                'sort' => 0,
                'class' => null,
                'menu_id' => 4,
                'depth' => 0,
                'created_at' => '2024-08-03 23:26:13',
                'updated_at' => '2024-08-03 23:26:25',
            ],
            [
                'id' => 12,
                'label' => 'Payment',
                'link' => '/payment',
                'parent_id' => 0,
                'sort' => 1,
                'class' => null,
                'menu_id' => 4,
                'depth' => 0,
                'created_at' => '2024-08-03 23:26:25',
                'updated_at' => '2024-08-03 23:26:37',
            ],
            [
                'id' => 13,
                'label' => 'Settings',
                'link' => '/settings',
                'parent_id' => 0,
                'sort' => 2,
                'class' => null,
                'menu_id' => 4,
                'depth' => 0,
                'created_at' => '2024-08-03 23:26:37',
                'updated_at' => '2024-08-03 23:26:50',
            ],
            [
                'id' => 14,
                'label' => 'Privacy Policy',
                'link' => '/policy',
                'parent_id' => 0,
                'sort' => 4,
                'class' => null,
                'menu_id' => 4,
                'depth' => 0,
                'created_at' => '2024-08-03 23:26:50',
                'updated_at' => '2024-08-03 23:26:50',
            ],
            [
                'id' => 15,
                'label' => 'Home',
                'link' => '/',
                'parent_id' => 0,
                'sort' => 0,
                'class' => null,
                'menu_id' => 1,
                'depth' => 0,
                'created_at' => '2024-08-04 10:12:06',
                'updated_at' => '2024-08-04 10:12:19',
            ],
            [
                'id' => 16,
                'label' => 'About',
                'link' => '/about',
                'parent_id' => 0,
                'sort' => 1,
                'class' => null,
                'menu_id' => 1,
                'depth' => 0,
                'created_at' => '2024-08-04 10:12:19',
                'updated_at' => '2024-08-04 10:12:42',
            ],
            [
                'id' => 17,
                'label' => 'Chefs',
                'link' => '/chef',
                'parent_id' => 22,
                'sort' => 5,
                'class' => null,
                'menu_id' => 1,
                'depth' => 1,
                'created_at' => '2024-08-04 10:12:42',
                'updated_at' => '2024-08-05 19:39:16',
            ],
            [
                'id' => 18,
                'label' => 'Blog',
                'link' => '/blogs',
                'parent_id' => 0,
                'sort' => 2,
                'class' => null,
                'menu_id' => 1,
                'depth' => 0,
                'created_at' => '2024-08-04 10:12:58',
                'updated_at' => '2024-08-04 11:27:21',
            ],
            [
                'id' => 19,
                'label' => 'Contact',
                'link' => '/contact',
                'parent_id' => 0,
                'sort' => 3,
                'class' => null,
                'menu_id' => 1,
                'depth' => 0,
                'created_at' => '2024-08-04 10:13:17',
                'updated_at' => '2024-08-04 11:27:21',
            ],
            [
                'id' => 20,
                'label' => 'Testimonial',
                'link' => '/testimonials',
                'parent_id' => 22,
                'sort' => 6,
                'class' => null,
                'menu_id' => 1,
                'depth' => 1,
                'created_at' => '2024-08-04 10:13:47',
                'updated_at' => '2024-08-05 19:39:16',
            ],
            [
                'id' => 21,
                'label' => 'Privacy Policy',
                'link' => '/privacy-policy',
                'parent_id' => 22,
                'sort' => 7,
                'class' => null,
                'menu_id' => 1,
                'depth' => 1,
                'created_at' => '2024-08-04 10:14:58',
                'updated_at' => '2024-08-04 11:27:21',
            ],
            [
                'id' => 22,
                'label' => 'Pages',
                'link' => '#',
                'parent_id' => 0,
                'sort' => 4,
                'class' => null,
                'menu_id' => 1,
                'depth' => 0,
                'created_at' => '2024-08-04 11:26:42',
                'updated_at' => '2024-08-04 11:27:31',
            ],
            [
                'id' => 24,
                'label' => 'Terms And Condition',
                'link' => '/page/terms-and-condition',
                'parent_id' => 22,
                'sort' => 8,
                'class' => null,
                'menu_id' => 1,
                'depth' => 1,
                'created_at' => '2024-08-04 17:45:46',
                'updated_at' => '2024-08-05 19:35:29',
            ],
            [
                'id' => 25,
                'label' => 'Products',
                'link' => '/products',
                'parent_id' => 0,
                'sort' => 9,
                'class' => null,
                'menu_id' => 1,
                'depth' => 0,
                'created_at' => '2024-08-05 19:35:29',
                'updated_at' => '2024-08-05 19:35:29',
            ],
        ];


        DB::table('admin_menus')->insert($admin_menus);
        DB::table('admin_menu_items')->insert($admin_menu_items);
    }
}
